name: Server Boost Reminder

on:
  schedule:
    - cron: "0 12 * * 3" # every wednesday
    - cron: "0 10 * * 6" # every saturday
  workflow_dispatch:

jobs:
  server-boost-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send Message to Discord
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          avatar-url: https://raw.githubusercontent.com/${{ github.repository }}/master/images/Profile%20Logo%20Nitro.png
          username: Seelen
          embed-color: 0xf47fff
          embed-title: Hi there! ✨
          embed-description: |
            ## Hey there, amazing community! ✨

            **Consider boosting our Discord server!** <:server_boost:1353983284618727525>

            ### 💜 Why Boost?
            ```diff
            + 🛠️ Directly supports Seelen UI development
            + 🌟 Unlock exclusive roles & server perks
            + 🎁 Help unlock community-wide benefits
            + ⚡ Get priority support access
            ```

            ### 🚀 How to Boost
            **Just click "Server Boost" next to the server name!**

            ━━━━━━━━━━━━━━━━━━━━━━━━
            *Even 1 boost makes a huge difference!*
            **#BoostToSupport** 💖
          embed-footer-text: "*#BoostToSupport*"
