name: Server Boost Reminder

on:
  schedule:
    - cron: "0 12 * * 3" # every wednesday
    - cron: "0 10 * * 6" # every saturday
  workflow_dispatch:

jobs:
  server-boost-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send Message to Discord
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          avatar-url: https://raw.githubusercontent.com/${{ github.repository }}/master/images/Profile%20Logo%20Nitro.png
          username: Seelen
          embed-color: 0xf47fff
          embed-image-url: https://raw.githubusercontent.com/${{ github.repository }}/master/images/discord_boost.jpg
